### ISSUE TITLE
Getting error in ios

### ISSUE THREAD

**Issue by Neelshah768** [NodeMedia/react-native-nodemediaclient#16]
I am successfully installed the package and installed pods for my iOS build. but after building project I am getting the below error.

error: Error: While trying to resolve module `react-native-nodemediaclient` from file `/Users/promethean/LivCast/livcast-app/src/screens/main/Live/CamLiveScreen.js`, the package `/Users/promethean/LivCast/livcast-app/node_modules/react-native-nodemediaclient/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/promethean/LivCast/livcast-app/node_modules/react-native-nodemediaclient/src/index`. Indeed, none of these files exist:

  * /Users/promethean/LivCast/livcast-app/node_modules/react-native-nodemediaclient/src/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/promethean/LivCast/livcast-app/node_modules/react-native-nodemediaclient/src/index/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/node-haste/DependencyGraph.js:243:17)
    at Object.resolve (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async traverseDependenciesForSingleFile (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async traverseDependencies (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:60:7)
    at async DeltaCalculator._getChangedDependencies (/Users/promethean/LivCast/livcast-app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:204:42)

**Comment by wszhutianyu** [comment]
same error

**Comment by 2313564566** [comment]
me too
