### ISSUE TITLE
App crash when proguard is enabled

### ISSUE THREAD

**Issue by matinzd** [NodeMedia/react-native-nodemediaclient#55]
App will crash when I try to enable progaurd .. 
```
java.lang.NoSuchMethodError: no non-static method "Lcn/nodemedia/NodePlayer;.onEvent(ILjava/lang/String;)V"
        at cn.nodemedia.NodePlayer.jniInit(Native Method)
        at cn.nodemedia.NodePlayer.<init>(Unknown Source:3)
        at cn.nodemedia.react_native_nodemediaclient.RCTNodePlayerView.<init>(Unknown Source:19)
        at cn.nodemedia.react_native_nodemediaclient.NodePlayerViewManager.createViewInstance(Unknown Source:2)
        at cn.nodemedia.react_native_nodemediaclient.NodePlayerViewManager.createViewInstance(Unknown Source:0)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(Unknown Source:0)
        at com.facebook.react.uimanager.ViewManager.createView(Unknown Source:0)
```

![image](https://user-images.githubusercontent.com/24797481/68069577-fd59cd80-fd76-11e9-8533-a095c1c3a5a6.png)

**Comment by Relati** [comment]
add proguard rule `-keep class cn.nodemedia.** {*;}` into android/app/proguard-rules.pro

**Comment by matinzd** [comment]
Thanks I solved it 3 days ago by adding this. Please add this to readme if
possible

**Comment by abbasmoosavi** [comment]
> Thanks I solved it 3 days ago by adding this. Please add this to readme if possible

Believe me, I have the this problem now. Kelly got me in trouble. I wish this was in readme
