### ISSUE TITLE
NodeCameraView  android 闪退

### ISSUE THREAD

**Issue by ngxu** [NodeMedia/react-native-nodemediaclient#89]
rn 0.62.2
android系统 10
"react-native-nodemediaclient": "^0.1.11",

报错信息
`
2020-06-15 10:01:39.799 16485-16658/com.mobilelawenforcement E/AndroidRuntime: FATAL EXCEPTION: GLThread 849
    Process: com.mobilelawenforcement, PID: 16485
    java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2199)
        at cn.nodemedia.NodeCameraView.getPreviewSize(NodeCameraView.java:168)
        at cn.nodemedia.NodeCameraView.onSurfaceChanged(NodeCameraView.java:307)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1566)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1281)

`

```javascript

<NodeCameraView

          style={{  width: touchMove ? pickerWidth :width , height: touchMove ? pickerHeight : WindowH, }}
          ref={(vb) => { this.vb = vb }}
          outputUrl={'xxxx'}
          Beauty={5}
          camera={{ cameraId: 0, cameraFrontMirror: false }}
          audio={{ bitrate: 32000, profile: 1, samplerate: 44100 }}
          video={{
            preset: 4, //分辨率尺寸 
            bitrate: 800000, //质量
            profile: 1,
            fps: 15,
            videoFrontMirror: false
          }}
          smoothSkinLevel={3}
        autopreview={true}
        onStatus={async (e)=>{await this.getLiveChange(e)}}
        />

```

**Comment by ngxu** [comment]
如果我去掉width，就不会闪退，但是漆黑一片，什么也没有

**Comment by ngxu** [comment]
```
<NodeCameraView

          style={{width:320,height:720}}
/>
```
如果设置width就闪退包上面的错，如果不设置width，能打开摄像头推流，但是没有画面。

**Comment by ngxu** [comment]
@illuspas 大兄弟，你好，能解决这个问题吗。

**Comment by ngxu** [comment]
我的rn项目 android/build.gradle

```
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29  
        targetSdkVersion = 29
    }
```

是因为使用了api29吗，由于有个库必须要把这了改成29，应该怎么做

**Comment by ngxu** [comment]
![image](https://user-images.githubusercontent.com/43433064/84617183-c8168000-af00-11ea-8c6e-ceaed47f2d55.png)
@illuspas

**Comment by ngxu** [comment]
![image](https://user-images.githubusercontent.com/43433064/84620628-1597ea80-af0b-11ea-802a-4ceec6d8fef0.png)

我修改成api28依然报同样的错

```java
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28  
        targetSdkVersion = 28
    }
```

**Comment by daxaxelrod** [comment]
Hi, I'm getting the same error

**Comment by daxaxelrod** [comment]
https://github.com/NodeMedia/NodeMediaClient-Android/blob/821cf3a200f820082741cef62b1727d9295038ec/nodemediaclient/src/main/java/cn/nodemedia/NodeCameraView.java#L167

Maybe the camera object needs more config to deal with layout changes?
